- name: minemeld playbook
  hosts: 127.0.0.1
  connection: local
  sudo: yes

  # remove comment to set custom repositories
  vars:
    core_repo: "https://github.com/mortfrog/minemeld-core.git"
    prototype_repo: "https://github.com/mortfrog/minemeld-node-prototypes.git"

  roles:
  - infrastructure
  - minemeld_devel
